### ISSUE TITLE
[dev webserver] file richiesti non presenti nel repo?

### ISSUE THREAD

**Issue by feroda** [ri-co/dummyPacketTracer#1]
Seguendo il README.md ottengo un errore su file non presenti.
In particolare `dPT_server/vendor/autoload.php`. Forse non sono stati aggiunti al repository?

Di seguito il mio comando e l'errore:

```
~/src/feroda/dummyPacketTracer$ php artisan serve
PHP Warning:  require(/home/fero/src/feroda/dummyPacketTracer/dPT_server/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/fero/src/feroda/dummyPacketTracer/dPT_server/bootstrap/autoload.php on line 17

Warning: require(/home/fero/src/feroda/dummyPacketTracer/dPT_server/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/fero/src/feroda/dummyPacketTracer/dPT_server/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/home/fero/src/feroda/dummyPacketTracer/dPT_server/bootstrap/../vendor/autoload.php' (include_path='.:') in /home/fero/src/feroda/dummyPacketTracer/dPT_server/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/home/fero/src/feroda/dummyPacketTracer/dPT_server/bootstrap/../vendor/autoload.php' (include_path='.:') in /home/fero/src/feroda/dummyPacketTracer/dPT_server/bootstrap/autoload.php on line 17
```

**Comment by ri-co** [comment]
composer deve essere installato sulla macchina e dovrebbe bastare il comando (nella directory dPT_server): 
`composer dump-autoload`

in caso non bastasse penso debba indicare a composer di scaricare le dipendende per laravel:
`composer require laravel/installer`

**Comment by feroda** [comment]
Grazie, sistemato! 
`$ composer dump-autoload` risolve il problema dell'inclusione del file `vendor/autoload.php`

`$ composer require laravel/installer` risolve il problema di classi non trovate all'avvio (giustamente se non ha il framework non può procedere all'avvio del tutto)
