### ISSUE TITLE
Errore nella query interfaces al database

### ISSUE THREAD

**Issue by ri-co** [ri-co/dummyPacketTracer#10]
https://github.com/ri-co/dummyPacketTracer/blob/master/dPT_server/app/Http/Controllers/HomeController.php#L55

e molto probabilmente anche

https://github.com/ri-co/dummyPacketTracer/blob/master/dPT_server/app/Http/Controllers/HomeController.php#L56

**Comment by feroda** [comment]
mi puoi dire come riprodurre l'errore?

**Comment by ri-co** [comment]
@feroda basta che apri un progetto dalla lista e vedi l'esito della richiesta GET /api/projects/:name nel debugger del browser

**Comment by feroda** [comment]
non riesco a riprodurlo, forse e' un problema legato al contenuto del tuo DB?

**Comment by feroda** [comment]
Il bug consiste nell'ultizzo di array_push che come primo parametro prende l'array cui aggiungere, e come secondo l'elemento da aggiungere (non so se come secondo parametro prende una lista di elementi).
